services:
  valheim:
    image: lloesche/valheim-server:latest
    container_name: valheim
    restart: unless-stopped
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
    volumes:
      - /data/games/valheim/config:/config
      - /data/games/valheim/data:/opt/valheim
    environment:
      SERVER_NAME: ${VALHEIM_SERVER_NAME}
      WORLD_NAME: ${VALHEIM_WORLD_NAME}
      SERVER_PASS: ${VALHEIM_SERVER_PASS}
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
